version: '3'

services:
    website:
        build: ./website
        volumes:
            - ./website:/var/www/html
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        ports:
            - 8000:80
